version: '3'
services:
  goapp:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/home
    depends_on:
      - mysql
    extra_hosts:
     - "host.docker.internal:172.17.0.1"
  
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cartola
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./sql_data:/var/lib/mysql