# Generated by Django 4.1.4 on 2022-12-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_myteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myteam',
            old_name='player',
            new_name='players',
        ),
    ]
